language: node_js
node_js:
- '0.8'
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
after-success:
  api_key:
    secure: ACeugC7AMroaK77IwGd/hrsWqudqU7HK2BbxIc/MkfxpqihwypVn3nFc3qquNiT0TIAele2bJlZnqwKzoFP5HXfcuegI/dJul+pcG7l427jNTqYZ1b0reUUS432I/SSHg7Rk7ywTd5FA1AYzJoDfT5AYVXfQ5m47a9giqDXBzh8=
  - git remote add heroku git@heroku.com:guarded-savannah-5374.git
  - git subtree push --prefix dist heroku master
